name: Deploy to AWS ECR

on:
  workflow_run:
    workflows: ["Docker Build"]
    types:
      - completed

jobs:
  push-to-ecr:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::<AWS_ACCOUNT_ID>:role/<ROLE_NAME>

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com

      - name: Download Docker Image Tag
        uses: actions/download-artifact@v4
        with:
          name: docker-tag
          path: .

      - name: Push to ECR
        run: |
          IMAGE_TAG=$(cat ${{ github.workspace }}/docker-tag)
          docker tag my-app:$IMAGE_TAG <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/my-app:$IMAGE_TAG
          docker push <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/my-app:$IMAGE_TAG
