name: Docker Build

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: .

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t my-app:latest .

      - name: Tag Docker Image
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)
          docker tag my-app:latest my-app:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Upload Docker Image Tag
        uses: actions/upload-artifact@v4
        with:
          name: docker-tag
          path: ${{ github.workspace }}
